import React, { useContext } from 'react';
import { useNavigate } from 'react-router-dom';
import { FileText, Download, Share2 } from 'lucide-react';
import { AnalysisContext } from '../context/AnalysisContext';
import { jsPDF } from 'jspdf';

function ResultsPage() {
  const navigate = useNavigate();
  const { analysisState } = useContext(AnalysisContext);

  // Determine verdict based on prediction
  const getVerdict = () => {
    if (analysisState.result?.prediction === 'FAKE') {
      return { label: 'ADULTERATED', color: 'bg-red-500', textColor: 'text-red-600' };
    }
    return { label: 'AUTHENTIC', color: 'bg-green-500', textColor: 'text-green-600' };
  };

  const verdict = getVerdict();
  const certainty = analysisState.result?.real_probability 
    ? Math.round(analysisState.result.real_probability * 100) 
    : 0;

  const handleExportPDF = () => {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    let yPosition = 20;
    const lineHeight = 7;
    const margin = 20;
    const maxWidth = pageWidth - 2 * margin;

    // Title
    doc.setFontSize(24);
    doc.setFont(undefined, 'bold');
    doc.text('VeriFake AI - Deepfake Analysis Report', pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 15;

    // Date
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text(`Analysis Date: ${new Date().toLocaleString()}`, margin, yPosition);
    yPosition += 10;

    // File Information
    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text('File Information', margin, yPosition);
    yPosition += 8;

    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text(`Filename: ${analysisState.fileName || 'Unknown'}`, margin, yPosition);
    yPosition += 6;
    doc.text(`Request ID: ${analysisState.requestId || 'N/A'}`, margin, yPosition);
    yPosition += 10;

    // Analysis Result
    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text('Analysis Results', margin, yPosition);
    yPosition += 8;

    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text('Verdict: AUTHENTIC', margin, yPosition);
    yPosition += 6;
    doc.text('Manipulation Probability: 0%', margin, yPosition);
    yPosition += 6;
    doc.text('Forensic Risk Score: 0%', margin, yPosition);
    yPosition += 10;

    // Forensic Report Section
    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text('Forensic Investigation Report', margin, yPosition);
    yPosition += 8;

    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    const reportText = 'The provided media has been analyzed using advanced AI forensic techniques. The analysis protocol evaluated multiple detection vectors including GAN-generated noise patterns, facial warping artifacts, photographic texture anomalies, and metadata inconsistencies. No significant manipulations or deepfake indicators were detected during this analysis.';
    
    const splitReport = doc.splitTextToSize(reportText, maxWidth);
    doc.text(splitReport, margin, yPosition);
    yPosition += splitReport.length * lineHeight + 5;

    // Detected Anomalies
    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text('Detected Anomalies', margin, yPosition);
    yPosition += 8;

    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text('No significant anomalies detected', margin, yPosition);
    yPosition += 10;

    // Content Metadata
    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text('Content Metadata', margin, yPosition);
    yPosition += 8;

    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text('Resolution: 2400x1200', margin, yPosition);
    yPosition += 6;
    doc.text('Format: PNG', margin, yPosition);
    yPosition += 10;

    // Footer
    doc.setFontSize(9);
    doc.setFont(undefined, 'italic');
    doc.text('This report is generated by VeriFace AI - Advanced Deepfake Detection System', pageWidth / 2, pageHeight - 10, { align: 'center' });

    // Save PDF
    const filename = `VeriFace_Analysis_${new Date().getTime()}.pdf`;
    doc.save(filename);
  };

  return (
    <main className="max-w-7xl mx-auto py-8 px-8 text-slate-900 dark:text-slate-100">
      {/* Header Actions */}
      <div className="flex justify-between items-center mb-8">
        <button
          onClick={() => navigate('/')}
          className="flex items-center gap-2 px-4 py-2 bg-slate-700 dark:bg-slate-800 text-white rounded-lg hover:bg-slate-600 dark:hover:bg-slate-700 transition-colors"
        >
          ← START NEW ANALYSIS
        </button>
        <div className="flex gap-4">
          <button 
            onClick={handleExportPDF}
            className="flex items-center gap-2 px-4 py-2 bg-slate-700 dark:bg-slate-800 text-white rounded-lg hover:bg-slate-600 dark:hover:bg-slate-700 transition-colors">
            <Download size={16} />
            EXPORT PDF
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Column - Main Analysis */}
        <div className="lg:col-span-2 space-y-6">
          {/* Media Display */}
          <div className="bg-white dark:bg-slate-800 rounded-2xl p-6 border border-slate-200 dark:border-slate-700">
            <div className="flex items-center gap-4 mb-6">
              <span className={`px-3 py-1 ${verdict.color} text-white text-xs font-bold rounded-full`}>
                {verdict.label}
              </span>
              <span className="px-3 py-1 bg-slate-200 dark:bg-slate-700 text-slate-700 dark:text-slate-300 text-xs font-bold rounded-full">
                {certainty}% CERTAINTY
              </span>
            </div>
            
            {/* Media Thumbnail Display */}
            <div className="relative w-full bg-slate-50 dark:bg-slate-900 rounded-lg overflow-hidden">
              {analysisState.fileType === 'image' && analysisState.mediaPreview ? (
                <img 
                  src={analysisState.mediaPreview} 
                  alt="uploaded media" 
                  className="w-full h-auto object-cover" 
                />
              ) : analysisState.fileType === 'video' && analysisState.mediaPreview ? (
                <img 
                  src={analysisState.mediaPreview} 
                  alt="video thumbnail" 
                  className="w-full h-64 object-cover" 
                />
              ) : analysisState.fileType === 'audio' ? (
                <div className="w-full h-64 bg-gradient-to-br from-blue-600 to-blue-900 flex items-center justify-center">
                  <div className="text-center">
                    <span className="text-6xl mb-4 block">🎵</span>
                    <p className="text-white text-lg">{analysisState.fileName}</p>
                  </div>
                </div>
              ) : (
                <div className="w-full h-64 bg-slate-200 dark:bg-slate-900 flex items-center justify-center">
                  <p className="text-slate-500 dark:text-slate-400">No media preview available</p>
                </div>
              )}
            </div>
          </div>

          {/* Forensic Report */}
          <div className="bg-white dark:bg-slate-800 rounded-2xl p-6 border border-slate-200 dark:border-slate-700">
            <div className="flex items-center gap-3 mb-4">
              <FileText size={20} className="text-blue-500" />
              <h2 className="text-xl font-bold text-slate-900 dark:text-white">
                Forensic Investigation Report
              </h2>
            </div>
            <p className="text-sm text-slate-600 dark:text-slate-300 leading-relaxed">
              The provided media is a digital data visualization (Gantt Chart) generated via plotting software (likely 
              Python/Matplotlib). The deepfake analysis protocol is inapplicable, as the image contains no human 
              subjects, faces, or biological features. There are no signs of GAN-generated noise, facial warping, or 
              photographic texture anomalies. The visual characteristics (crisp lines, uniform fonts, solid colors) are 
              consistent with authentic vector-based or rasterized computer graphics, not manipulated photographic 
              media.
            </p>
          </div>
        </div>

        {/* Right Column - Stats */}
        <div className="space-y-6">
          {/* Manipulation Probability */}
          <div className="bg-white dark:bg-slate-800 rounded-2xl p-6 border border-slate-200 dark:border-slate-700">
            <h3 className="text-lg font-bold text-slate-900 dark:text-white mb-6">
              Manipulation Probability
            </h3>
            <div className="flex flex-col items-center">
              <div className="relative w-48 h-48">
                <svg className="w-full h-full transform -rotate-90">
                  <circle
                    cx="96"
                    cy="96"
                    r="80"
                    stroke="currentColor"
                    strokeWidth="12"
                    fill="none"
                    className="text-slate-700 dark:text-slate-600"
                  />
                  <circle
                    cx="96"
                    cy="96"
                    r="80"
                    stroke="currentColor"
                    strokeWidth="12"
                    fill="none"
                    strokeDasharray="502.4"
                    strokeDashoffset={analysisState.result?.prediction === 'FAKE' ? '100' : '502.4'}
                    className={analysisState.result?.prediction === 'FAKE' ? 'text-red-500' : 'text-green-500'}
                  />
                </svg>
                <div className="absolute inset-0 flex flex-col items-center justify-center">
                  <span className="text-5xl font-bold text-slate-900 dark:text-white">
                    {analysisState.result?.prediction === 'FAKE' ? '100' : '0'}%
                  </span>
                </div>
              </div>
              <p className="text-sm text-slate-500 dark:text-slate-400 mt-4">Forensic Risk Score</p>
            </div>
          </div>

          {/* Detected Anomalies */}
          <div className="bg-white dark:bg-slate-800 rounded-2xl p-6 border border-slate-200 dark:border-slate-700">
            <div className="flex items-center gap-2 mb-4">
              <span className="text-yellow-500">⚠️</span>
              <h3 className="text-lg font-bold text-slate-900 dark:text-white">
                Detected Anomalies
              </h3>
            </div>
            <p className="text-sm text-slate-500 dark:text-slate-400 italic">
              No significant anomalies detected
            </p>
          </div>

          {/* Content Metadata */}
          <div className="bg-white dark:bg-slate-800 rounded-2xl p-6 border border-slate-200 dark:border-slate-700">
            <h3 className="text-lg font-bold text-slate-900 dark:text-white mb-4">
              Content Metadata
            </h3>
            <div className="space-y-3">
              <div>
                <p className="text-xs text-slate-500 dark:text-slate-400 uppercase mb-1">Resolution</p>
                <p className="text-sm font-semibold text-slate-900 dark:text-white">2400x1200</p>
              </div>
              <div>
                <p className="text-xs text-slate-500 dark:text-slate-400 uppercase mb-1">Format</p>
                <p className="text-sm font-semibold text-slate-900 dark:text-white">PNG</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}

export default ResultsPage;
